language: node_js
node_js:
- '0.11'
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install
- bower install
script:
- grunt karma:ci
after_script:
- grunt coveralls
addons:
  sauce_connect: true
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
